### ISSUE TITLE
Add a smile emoji in Readme.md

### ISSUE THREAD

**Issue by samrath-sudesh-acharya** [samrath-sudesh-acharya/demo#5]
the code for smile emoji is 
```markdown
:smile:
```

**Comment by aneeeeesha** [comment]
I think I can do this

**Comment by samrath-sudesh-acharya** [comment]
ok great go for it

**Comment by aneeeeesha** [comment]
Cool!

**Comment by aneeeeesha** [comment]
Done,I have sent a pull request!
Do tell me if I have there are any issues.

**Comment by aneeeeesha** [comment]
![image](https://user-images.githubusercontent.com/84973812/123679024-a74b6f00-d864-11eb-95f2-d8c1f8a64376.png)
Here is the image

**Comment by samrath-sudesh-acharya** [comment]
what is this @aneeeeesha 
PLease i need a emoji

**Comment by aneeeeesha** [comment]
Sir,now sir?

**Comment by samrath-sudesh-acharya** [comment]
close #5
